import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/provider/provider";
import BottomTabs from "@/components/shared/BottomTabs";
// import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster as HotToaster } from "react-hot-toast";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VisitFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <Providers>
                <div className="pb-20">{children}</div>
                <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
          >
                <BottomTabs />
                <Toaster position="top-center"/>
                <HotToaster
  position="top-center"
  reverseOrder={false}
/>


    </ThemeProvider>
              </Providers>
      </body>
    </html>
  );
}
